FROM eclipse-temurin:17-jdk-alpine
WORKDIR /usr/lib
ADD ./target/KanbanService-0.0.1-SNAPSHOT.jar /usr/lib/KanbanService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","KanbanService-0.0.1-SNAPSHOT.jar"]